environment:
  matrix:
    - nodejs_version: 7

test_script:
  - node --version
  - yarn --version
  - yarn test

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - yarn

cache:
  - "%LOCALAPPDATA%/Yarn"

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1
