strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

variables:
  azureContainerRegistry: Contoso
  azureSubscriptionEndpoint: Contoso

steps:
- task: DockerCompose@0
  displayName: Container registry login
  inputs:
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- script: docker-compose up -d && yarn && yarn test
