mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=compat-db
    - MYSQL_USER=username
    - MYSQL_PASSWORD=secret
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
