// flow-typed signature: 21d0f698f2dc5c07cf7e5d727f879409
// flow-typed version: <<STUB>>/caniuse-db_v1.0.30000622/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caniuse-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'caniuse-db' {
  declare module.exports: any;
}
