// flow-typed signature: b2a421cfe1684d9fe9679ddf7894f9b6
// flow-typed version: <<STUB>>/caniuse-db_v1.0.30000940/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caniuse-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'caniuse-db' {
  declare module.exports: any;
}
