// flow-typed signature: 2acb8c56d6c55f8e7c9b552b7cf89e31
// flow-typed version: <<STUB>>/caniuse-db_v1.0.30000632/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caniuse-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'caniuse-db' {
  declare module.exports: any;
}
