// flow-typed signature: 72b5873b2636d397dd44b42a850ca778
// flow-typed version: <<STUB>>/download-cli_v^1.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'download-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'download-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'download-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'download-cli/cli.js' {
  declare module.exports: $Exports<'download-cli/cli'>;
}
