// flow-typed signature: 8f3f0602b5e88f5052ee506512eb57ea
// flow-typed version: <<STUB>>/eslint-config-bliss_v^0.0.7/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-bliss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-bliss' {
  declare module.exports: any;
}
