// flow-typed signature: 05a7f825f59ac6e886fc93cea102f2b5
// flow-typed version: <<STUB>>/http-server_v^0.11.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-server/lib/http-server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-server/lib/http-server.js' {
  declare module.exports: $Exports<'http-server/lib/http-server'>;
}
