// flow-typed signature: e61b176d37569ef43e6d023e5fda56b0
// flow-typed version: <<STUB>>/jasmine-async-test_v^0.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-async-test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-async-test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-async-test/spec/asyncTestSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-async-test/index' {
  declare module.exports: $Exports<'jasmine-async-test'>;
}
declare module 'jasmine-async-test/index.js' {
  declare module.exports: $Exports<'jasmine-async-test'>;
}
declare module 'jasmine-async-test/spec/asyncTestSpec.js' {
  declare module.exports: $Exports<'jasmine-async-test/spec/asyncTestSpec'>;
}
