// flow-typed signature: f71233222f384a75fe21340b26c32dc6
// flow-typed version: <<STUB>>/mysql_v^2.13.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mysql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mysql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mysql/lib/Connection' {
  declare module.exports: any;
}

declare module 'mysql/lib/ConnectionConfig' {
  declare module.exports: any;
}

declare module 'mysql/lib/Pool' {
  declare module.exports: any;
}

declare module 'mysql/lib/PoolCluster' {
  declare module.exports: any;
}

declare module 'mysql/lib/PoolConfig' {
  declare module.exports: any;
}

declare module 'mysql/lib/PoolConnection' {
  declare module.exports: any;
}

declare module 'mysql/lib/PoolNamespace' {
  declare module.exports: any;
}

declare module 'mysql/lib/PoolSelector' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/Auth' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/BufferList' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/constants/charsets' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/constants/client' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/constants/errors' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/constants/field_flags' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/constants/server_status' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/constants/ssl_profiles' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/constants/types' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/PacketHeader' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/ClientAuthenticationPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/ComChangeUserPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/ComPingPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/ComQueryPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/ComQuitPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/ComStatisticsPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/EmptyPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/EofPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/ErrorPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/Field' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/FieldPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/HandshakeInitializationPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/index' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/LocalDataFilePacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/OkPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/OldPasswordPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/ResultSetHeaderPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/RowDataPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/SSLRequestPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/StatisticsPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/packets/UseOldPasswordPacket' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/PacketWriter' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/Parser' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/Protocol' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/ResultSet' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/sequences/ChangeUser' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/sequences/Handshake' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/sequences/index' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/sequences/Ping' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/sequences/Query' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/sequences/Quit' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/sequences/Sequence' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/sequences/Statistics' {
  declare module.exports: any;
}

declare module 'mysql/lib/protocol/SqlString' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mysql/index' {
  declare module.exports: $Exports<'mysql'>;
}
declare module 'mysql/index.js' {
  declare module.exports: $Exports<'mysql'>;
}
declare module 'mysql/lib/Connection.js' {
  declare module.exports: $Exports<'mysql/lib/Connection'>;
}
declare module 'mysql/lib/ConnectionConfig.js' {
  declare module.exports: $Exports<'mysql/lib/ConnectionConfig'>;
}
declare module 'mysql/lib/Pool.js' {
  declare module.exports: $Exports<'mysql/lib/Pool'>;
}
declare module 'mysql/lib/PoolCluster.js' {
  declare module.exports: $Exports<'mysql/lib/PoolCluster'>;
}
declare module 'mysql/lib/PoolConfig.js' {
  declare module.exports: $Exports<'mysql/lib/PoolConfig'>;
}
declare module 'mysql/lib/PoolConnection.js' {
  declare module.exports: $Exports<'mysql/lib/PoolConnection'>;
}
declare module 'mysql/lib/PoolNamespace.js' {
  declare module.exports: $Exports<'mysql/lib/PoolNamespace'>;
}
declare module 'mysql/lib/PoolSelector.js' {
  declare module.exports: $Exports<'mysql/lib/PoolSelector'>;
}
declare module 'mysql/lib/protocol/Auth.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/Auth'>;
}
declare module 'mysql/lib/protocol/BufferList.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/BufferList'>;
}
declare module 'mysql/lib/protocol/constants/charsets.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/constants/charsets'>;
}
declare module 'mysql/lib/protocol/constants/client.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/constants/client'>;
}
declare module 'mysql/lib/protocol/constants/errors.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/constants/errors'>;
}
declare module 'mysql/lib/protocol/constants/field_flags.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/constants/field_flags'>;
}
declare module 'mysql/lib/protocol/constants/server_status.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/constants/server_status'>;
}
declare module 'mysql/lib/protocol/constants/ssl_profiles.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/constants/ssl_profiles'>;
}
declare module 'mysql/lib/protocol/constants/types.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/constants/types'>;
}
declare module 'mysql/lib/protocol/PacketHeader.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/PacketHeader'>;
}
declare module 'mysql/lib/protocol/packets/ClientAuthenticationPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/ClientAuthenticationPacket'>;
}
declare module 'mysql/lib/protocol/packets/ComChangeUserPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/ComChangeUserPacket'>;
}
declare module 'mysql/lib/protocol/packets/ComPingPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/ComPingPacket'>;
}
declare module 'mysql/lib/protocol/packets/ComQueryPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/ComQueryPacket'>;
}
declare module 'mysql/lib/protocol/packets/ComQuitPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/ComQuitPacket'>;
}
declare module 'mysql/lib/protocol/packets/ComStatisticsPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/ComStatisticsPacket'>;
}
declare module 'mysql/lib/protocol/packets/EmptyPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/EmptyPacket'>;
}
declare module 'mysql/lib/protocol/packets/EofPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/EofPacket'>;
}
declare module 'mysql/lib/protocol/packets/ErrorPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/ErrorPacket'>;
}
declare module 'mysql/lib/protocol/packets/Field.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/Field'>;
}
declare module 'mysql/lib/protocol/packets/FieldPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/FieldPacket'>;
}
declare module 'mysql/lib/protocol/packets/HandshakeInitializationPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/HandshakeInitializationPacket'>;
}
declare module 'mysql/lib/protocol/packets/index.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/index'>;
}
declare module 'mysql/lib/protocol/packets/LocalDataFilePacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/LocalDataFilePacket'>;
}
declare module 'mysql/lib/protocol/packets/OkPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/OkPacket'>;
}
declare module 'mysql/lib/protocol/packets/OldPasswordPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/OldPasswordPacket'>;
}
declare module 'mysql/lib/protocol/packets/ResultSetHeaderPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/ResultSetHeaderPacket'>;
}
declare module 'mysql/lib/protocol/packets/RowDataPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/RowDataPacket'>;
}
declare module 'mysql/lib/protocol/packets/SSLRequestPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/SSLRequestPacket'>;
}
declare module 'mysql/lib/protocol/packets/StatisticsPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/StatisticsPacket'>;
}
declare module 'mysql/lib/protocol/packets/UseOldPasswordPacket.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/packets/UseOldPasswordPacket'>;
}
declare module 'mysql/lib/protocol/PacketWriter.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/PacketWriter'>;
}
declare module 'mysql/lib/protocol/Parser.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/Parser'>;
}
declare module 'mysql/lib/protocol/Protocol.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/Protocol'>;
}
declare module 'mysql/lib/protocol/ResultSet.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/ResultSet'>;
}
declare module 'mysql/lib/protocol/sequences/ChangeUser.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/sequences/ChangeUser'>;
}
declare module 'mysql/lib/protocol/sequences/Handshake.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/sequences/Handshake'>;
}
declare module 'mysql/lib/protocol/sequences/index.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/sequences/index'>;
}
declare module 'mysql/lib/protocol/sequences/Ping.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/sequences/Ping'>;
}
declare module 'mysql/lib/protocol/sequences/Query.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/sequences/Query'>;
}
declare module 'mysql/lib/protocol/sequences/Quit.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/sequences/Quit'>;
}
declare module 'mysql/lib/protocol/sequences/Sequence.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/sequences/Sequence'>;
}
declare module 'mysql/lib/protocol/sequences/Statistics.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/sequences/Statistics'>;
}
declare module 'mysql/lib/protocol/SqlString.js' {
  declare module.exports: $Exports<'mysql/lib/protocol/SqlString'>;
}
