// flow-typed signature: 44fd3aab96b4041d1e382cbb6df4966e
// flow-typed version: <<STUB>>/selenium-webdriver_v^3.1.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'selenium-webdriver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'selenium-webdriver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'selenium-webdriver/chrome' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/edge' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/example/chrome_android' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/example/chrome_mobile_emulation' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/example/firefox_channels' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/example/google_search_generator' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/example/google_search_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/example/google_search' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/example/logging' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/example/parallel_flows' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/firefox/binary' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/firefox/extension' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/firefox/index' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/firefox/profile' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/http/index' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/http/util' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/ie' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/io/exec' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/io/index' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/actions' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/atoms/getAttribute' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/atoms/is-displayed' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/by' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/capabilities' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/command' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/devmode' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/error' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/events' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/http' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/input' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/logging' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/promise' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/proxy' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/session' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/symbols' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/build' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/data/html5/database' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/data/html5/geolocation' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/data/jquery-1.3.2' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/data/js/jquery-1.4.4.min' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/data/js/jquery-ui-1.8.10.custom.min' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/data/js/themes/modern/theme.min' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/data/js/tinymce.min' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/data/screen/screen' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/fileserver' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/httpserver' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/index' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/promise' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/test/resources' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/until' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/lib/webdriver' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/net/index' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/net/portprober' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/opera' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/phantomjs' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/proxy' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/remote/index' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/safari' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/actions_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/chrome/options_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/chrome/service_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/cookie_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/element_finding_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/execute_script_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/fingerprint_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/firefox/extension_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/firefox/firefox_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/firefox/profile_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/http/http_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/http/util_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/io_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/by_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/capabilities_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/error_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/events_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/http_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/logging_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/promise_aplus_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/promise_error_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/promise_flow_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/promise_generator_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/promise_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/testutil' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/until_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/lib/webdriver_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/logging_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/net/index_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/net/portprober_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/page_loading_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/phantomjs/execute_phantomjs_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/proxy_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/rect_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/remote_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/safari_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/session_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/stale_element_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/tag_name_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/testing/assert_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/testing/index_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/upload_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/test/window_test' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/testing/assert' {
  declare module.exports: any;
}

declare module 'selenium-webdriver/testing/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'selenium-webdriver/chrome.js' {
  declare module.exports: $Exports<'selenium-webdriver/chrome'>;
}
declare module 'selenium-webdriver/edge.js' {
  declare module.exports: $Exports<'selenium-webdriver/edge'>;
}
declare module 'selenium-webdriver/example/chrome_android.js' {
  declare module.exports: $Exports<'selenium-webdriver/example/chrome_android'>;
}
declare module 'selenium-webdriver/example/chrome_mobile_emulation.js' {
  declare module.exports: $Exports<'selenium-webdriver/example/chrome_mobile_emulation'>;
}
declare module 'selenium-webdriver/example/firefox_channels.js' {
  declare module.exports: $Exports<'selenium-webdriver/example/firefox_channels'>;
}
declare module 'selenium-webdriver/example/google_search_generator.js' {
  declare module.exports: $Exports<'selenium-webdriver/example/google_search_generator'>;
}
declare module 'selenium-webdriver/example/google_search_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/example/google_search_test'>;
}
declare module 'selenium-webdriver/example/google_search.js' {
  declare module.exports: $Exports<'selenium-webdriver/example/google_search'>;
}
declare module 'selenium-webdriver/example/logging.js' {
  declare module.exports: $Exports<'selenium-webdriver/example/logging'>;
}
declare module 'selenium-webdriver/example/parallel_flows.js' {
  declare module.exports: $Exports<'selenium-webdriver/example/parallel_flows'>;
}
declare module 'selenium-webdriver/firefox/binary.js' {
  declare module.exports: $Exports<'selenium-webdriver/firefox/binary'>;
}
declare module 'selenium-webdriver/firefox/extension.js' {
  declare module.exports: $Exports<'selenium-webdriver/firefox/extension'>;
}
declare module 'selenium-webdriver/firefox/index.js' {
  declare module.exports: $Exports<'selenium-webdriver/firefox/index'>;
}
declare module 'selenium-webdriver/firefox/profile.js' {
  declare module.exports: $Exports<'selenium-webdriver/firefox/profile'>;
}
declare module 'selenium-webdriver/http/index.js' {
  declare module.exports: $Exports<'selenium-webdriver/http/index'>;
}
declare module 'selenium-webdriver/http/util.js' {
  declare module.exports: $Exports<'selenium-webdriver/http/util'>;
}
declare module 'selenium-webdriver/ie.js' {
  declare module.exports: $Exports<'selenium-webdriver/ie'>;
}
declare module 'selenium-webdriver/index' {
  declare module.exports: $Exports<'selenium-webdriver'>;
}
declare module 'selenium-webdriver/index.js' {
  declare module.exports: $Exports<'selenium-webdriver'>;
}
declare module 'selenium-webdriver/io/exec.js' {
  declare module.exports: $Exports<'selenium-webdriver/io/exec'>;
}
declare module 'selenium-webdriver/io/index.js' {
  declare module.exports: $Exports<'selenium-webdriver/io/index'>;
}
declare module 'selenium-webdriver/lib/actions.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/actions'>;
}
declare module 'selenium-webdriver/lib/atoms/getAttribute.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/atoms/getAttribute'>;
}
declare module 'selenium-webdriver/lib/atoms/is-displayed.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/atoms/is-displayed'>;
}
declare module 'selenium-webdriver/lib/by.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/by'>;
}
declare module 'selenium-webdriver/lib/capabilities.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/capabilities'>;
}
declare module 'selenium-webdriver/lib/command.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/command'>;
}
declare module 'selenium-webdriver/lib/devmode.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/devmode'>;
}
declare module 'selenium-webdriver/lib/error.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/error'>;
}
declare module 'selenium-webdriver/lib/events.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/events'>;
}
declare module 'selenium-webdriver/lib/http.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/http'>;
}
declare module 'selenium-webdriver/lib/input.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/input'>;
}
declare module 'selenium-webdriver/lib/logging.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/logging'>;
}
declare module 'selenium-webdriver/lib/promise.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/promise'>;
}
declare module 'selenium-webdriver/lib/proxy.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/proxy'>;
}
declare module 'selenium-webdriver/lib/session.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/session'>;
}
declare module 'selenium-webdriver/lib/symbols.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/symbols'>;
}
declare module 'selenium-webdriver/lib/test/build.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/build'>;
}
declare module 'selenium-webdriver/lib/test/data/html5/database.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/data/html5/database'>;
}
declare module 'selenium-webdriver/lib/test/data/html5/geolocation.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/data/html5/geolocation'>;
}
declare module 'selenium-webdriver/lib/test/data/jquery-1.3.2.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/data/jquery-1.3.2'>;
}
declare module 'selenium-webdriver/lib/test/data/js/jquery-1.4.4.min.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/data/js/jquery-1.4.4.min'>;
}
declare module 'selenium-webdriver/lib/test/data/js/jquery-ui-1.8.10.custom.min.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/data/js/jquery-ui-1.8.10.custom.min'>;
}
declare module 'selenium-webdriver/lib/test/data/js/themes/modern/theme.min.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/data/js/themes/modern/theme.min'>;
}
declare module 'selenium-webdriver/lib/test/data/js/tinymce.min.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/data/js/tinymce.min'>;
}
declare module 'selenium-webdriver/lib/test/data/screen/screen.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/data/screen/screen'>;
}
declare module 'selenium-webdriver/lib/test/fileserver.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/fileserver'>;
}
declare module 'selenium-webdriver/lib/test/httpserver.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/httpserver'>;
}
declare module 'selenium-webdriver/lib/test/index.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/index'>;
}
declare module 'selenium-webdriver/lib/test/promise.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/promise'>;
}
declare module 'selenium-webdriver/lib/test/resources.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/test/resources'>;
}
declare module 'selenium-webdriver/lib/until.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/until'>;
}
declare module 'selenium-webdriver/lib/webdriver.js' {
  declare module.exports: $Exports<'selenium-webdriver/lib/webdriver'>;
}
declare module 'selenium-webdriver/net/index.js' {
  declare module.exports: $Exports<'selenium-webdriver/net/index'>;
}
declare module 'selenium-webdriver/net/portprober.js' {
  declare module.exports: $Exports<'selenium-webdriver/net/portprober'>;
}
declare module 'selenium-webdriver/opera.js' {
  declare module.exports: $Exports<'selenium-webdriver/opera'>;
}
declare module 'selenium-webdriver/phantomjs.js' {
  declare module.exports: $Exports<'selenium-webdriver/phantomjs'>;
}
declare module 'selenium-webdriver/proxy.js' {
  declare module.exports: $Exports<'selenium-webdriver/proxy'>;
}
declare module 'selenium-webdriver/remote/index.js' {
  declare module.exports: $Exports<'selenium-webdriver/remote/index'>;
}
declare module 'selenium-webdriver/safari.js' {
  declare module.exports: $Exports<'selenium-webdriver/safari'>;
}
declare module 'selenium-webdriver/test/actions_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/actions_test'>;
}
declare module 'selenium-webdriver/test/chrome/options_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/chrome/options_test'>;
}
declare module 'selenium-webdriver/test/chrome/service_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/chrome/service_test'>;
}
declare module 'selenium-webdriver/test/cookie_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/cookie_test'>;
}
declare module 'selenium-webdriver/test/element_finding_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/element_finding_test'>;
}
declare module 'selenium-webdriver/test/execute_script_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/execute_script_test'>;
}
declare module 'selenium-webdriver/test/fingerprint_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/fingerprint_test'>;
}
declare module 'selenium-webdriver/test/firefox/extension_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/firefox/extension_test'>;
}
declare module 'selenium-webdriver/test/firefox/firefox_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/firefox/firefox_test'>;
}
declare module 'selenium-webdriver/test/firefox/profile_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/firefox/profile_test'>;
}
declare module 'selenium-webdriver/test/http/http_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/http/http_test'>;
}
declare module 'selenium-webdriver/test/http/util_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/http/util_test'>;
}
declare module 'selenium-webdriver/test/io_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/io_test'>;
}
declare module 'selenium-webdriver/test/lib/by_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/by_test'>;
}
declare module 'selenium-webdriver/test/lib/capabilities_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/capabilities_test'>;
}
declare module 'selenium-webdriver/test/lib/error_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/error_test'>;
}
declare module 'selenium-webdriver/test/lib/events_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/events_test'>;
}
declare module 'selenium-webdriver/test/lib/http_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/http_test'>;
}
declare module 'selenium-webdriver/test/lib/logging_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/logging_test'>;
}
declare module 'selenium-webdriver/test/lib/promise_aplus_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/promise_aplus_test'>;
}
declare module 'selenium-webdriver/test/lib/promise_error_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/promise_error_test'>;
}
declare module 'selenium-webdriver/test/lib/promise_flow_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/promise_flow_test'>;
}
declare module 'selenium-webdriver/test/lib/promise_generator_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/promise_generator_test'>;
}
declare module 'selenium-webdriver/test/lib/promise_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/promise_test'>;
}
declare module 'selenium-webdriver/test/lib/testutil.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/testutil'>;
}
declare module 'selenium-webdriver/test/lib/until_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/until_test'>;
}
declare module 'selenium-webdriver/test/lib/webdriver_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/lib/webdriver_test'>;
}
declare module 'selenium-webdriver/test/logging_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/logging_test'>;
}
declare module 'selenium-webdriver/test/net/index_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/net/index_test'>;
}
declare module 'selenium-webdriver/test/net/portprober_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/net/portprober_test'>;
}
declare module 'selenium-webdriver/test/page_loading_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/page_loading_test'>;
}
declare module 'selenium-webdriver/test/phantomjs/execute_phantomjs_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/phantomjs/execute_phantomjs_test'>;
}
declare module 'selenium-webdriver/test/proxy_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/proxy_test'>;
}
declare module 'selenium-webdriver/test/rect_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/rect_test'>;
}
declare module 'selenium-webdriver/test/remote_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/remote_test'>;
}
declare module 'selenium-webdriver/test/safari_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/safari_test'>;
}
declare module 'selenium-webdriver/test/session_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/session_test'>;
}
declare module 'selenium-webdriver/test/stale_element_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/stale_element_test'>;
}
declare module 'selenium-webdriver/test/tag_name_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/tag_name_test'>;
}
declare module 'selenium-webdriver/test/testing/assert_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/testing/assert_test'>;
}
declare module 'selenium-webdriver/test/testing/index_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/testing/index_test'>;
}
declare module 'selenium-webdriver/test/upload_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/upload_test'>;
}
declare module 'selenium-webdriver/test/window_test.js' {
  declare module.exports: $Exports<'selenium-webdriver/test/window_test'>;
}
declare module 'selenium-webdriver/testing/assert.js' {
  declare module.exports: $Exports<'selenium-webdriver/testing/assert'>;
}
declare module 'selenium-webdriver/testing/index.js' {
  declare module.exports: $Exports<'selenium-webdriver/testing/index'>;
}
