// flow-typed signature: c5d94929b809c5c9fea06761e2a0b167
// flow-typed version: <<STUB>>/tern-node-express_v^0.4.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tern-node-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tern-node-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tern-node-express/node-express' {
  declare module.exports: any;
}

declare module 'tern-node-express/scripts/git-tag' {
  declare module.exports: any;
}

declare module 'tern-node-express/test/run' {
  declare module.exports: any;
}

declare module 'tern-node-express/test/test_completion' {
  declare module.exports: any;
}

declare module 'tern-node-express/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tern-node-express/node-express.js' {
  declare module.exports: $Exports<'tern-node-express/node-express'>;
}
declare module 'tern-node-express/scripts/git-tag.js' {
  declare module.exports: $Exports<'tern-node-express/scripts/git-tag'>;
}
declare module 'tern-node-express/test/run.js' {
  declare module.exports: $Exports<'tern-node-express/test/run'>;
}
declare module 'tern-node-express/test/test_completion.js' {
  declare module.exports: $Exports<'tern-node-express/test/test_completion'>;
}
declare module 'tern-node-express/test/util.js' {
  declare module.exports: $Exports<'tern-node-express/test/util'>;
}
