// flow-typed signature: 5cf8332011afdb55892c8e778ed1f6ac
// flow-typed version: <<STUB>>/wdio-sauce-service_v^0.4.14/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio-sauce-service'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio-sauce-service' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio-sauce-service/build/sauce-launch-service' {
  declare module.exports: any;
}

declare module 'wdio-sauce-service/build/sauce-service' {
  declare module.exports: any;
}

declare module 'wdio-sauce-service/launcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio-sauce-service/build/sauce-launch-service.js' {
  declare module.exports: $Exports<'wdio-sauce-service/build/sauce-launch-service'>;
}
declare module 'wdio-sauce-service/build/sauce-service.js' {
  declare module.exports: $Exports<'wdio-sauce-service/build/sauce-service'>;
}
declare module 'wdio-sauce-service/index' {
  declare module.exports: $Exports<'wdio-sauce-service'>;
}
declare module 'wdio-sauce-service/index.js' {
  declare module.exports: $Exports<'wdio-sauce-service'>;
}
declare module 'wdio-sauce-service/launcher.js' {
  declare module.exports: $Exports<'wdio-sauce-service/launcher'>;
}
