// flow-typed signature: 4068d55d5cffcb545fbdb0237ac043b1
// flow-typed version: <<STUB>>/wdio-mocha-framework_v^0.5.8/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio-mocha-framework'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio-mocha-framework' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio-mocha-framework/build/adapter' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/gruntfile' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/lib/adapter' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/adapter.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/error.handling.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/error.handling.async.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/error.handling.promise.async.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/error.handling.promise.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/error.handling.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/hooks.using.async.conf' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/hooks.using.custom.commands' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/hooks.using.native.promises' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/hooks.using.q.promises' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/hooks.using.wdio.commands' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/sample.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/sample2.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/sample3.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/sample4.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/sample5.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/tests.async.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/tests.only.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/tests.options.compilers' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/tests.options.compilers.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/tests.options.require' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/tests.options.require.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/tests.retry.async.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/tests.retry.sync.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/tests.sync.async.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/fixtures/tests.sync.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/hooks.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/options.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/retry.spec' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/test/tests.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio-mocha-framework/build/adapter.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/build/adapter'>;
}
declare module 'wdio-mocha-framework/gruntfile.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/gruntfile'>;
}
declare module 'wdio-mocha-framework/lib/adapter.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/lib/adapter'>;
}
declare module 'wdio-mocha-framework/test/adapter.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/adapter.spec'>;
}
declare module 'wdio-mocha-framework/test/error.handling.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/error.handling.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/error.handling.async.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/error.handling.async.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/error.handling.promise.async.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/error.handling.promise.async.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/error.handling.promise.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/error.handling.promise.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/error.handling.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/error.handling.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/hooks.using.async.conf.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/hooks.using.async.conf'>;
}
declare module 'wdio-mocha-framework/test/fixtures/hooks.using.custom.commands.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/hooks.using.custom.commands'>;
}
declare module 'wdio-mocha-framework/test/fixtures/hooks.using.native.promises.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/hooks.using.native.promises'>;
}
declare module 'wdio-mocha-framework/test/fixtures/hooks.using.q.promises.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/hooks.using.q.promises'>;
}
declare module 'wdio-mocha-framework/test/fixtures/hooks.using.wdio.commands.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/hooks.using.wdio.commands'>;
}
declare module 'wdio-mocha-framework/test/fixtures/sample.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/sample.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/sample2.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/sample2.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/sample3.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/sample3.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/sample4.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/sample4.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/sample5.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/sample5.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/tests.async.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/tests.async.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/tests.only.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/tests.only.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/tests.options.compilers.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/tests.options.compilers'>;
}
declare module 'wdio-mocha-framework/test/fixtures/tests.options.compilers.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/tests.options.compilers.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/tests.options.require.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/tests.options.require'>;
}
declare module 'wdio-mocha-framework/test/fixtures/tests.options.require.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/tests.options.require.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/tests.retry.async.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/tests.retry.async.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/tests.retry.sync.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/tests.retry.sync.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/tests.sync.async.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/tests.sync.async.spec'>;
}
declare module 'wdio-mocha-framework/test/fixtures/tests.sync.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/fixtures/tests.sync.spec'>;
}
declare module 'wdio-mocha-framework/test/hooks.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/hooks.spec'>;
}
declare module 'wdio-mocha-framework/test/options.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/options.spec'>;
}
declare module 'wdio-mocha-framework/test/retry.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/retry.spec'>;
}
declare module 'wdio-mocha-framework/test/tests.spec.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/test/tests.spec'>;
}
