// flow-typed signature: f0604b981355370c236910aac870780f
// flow-typed version: <<STUB>>/webdriverio_v^5.6.6/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webdriverio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webdriverio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webdriverio/build/commands/browser/$' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/$$' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/call' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/debug' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/deleteCookies' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/execute' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/executeAsync' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/getCookies' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/keys' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/newWindow' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/pause' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/reloadSession' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/saveScreenshot' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/setCookies' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/setTimeout' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/switchWindow' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/touchAction' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/url' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/browser/waitUntil' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/constant' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/$' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/$$' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/addValue' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/clearValue' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/click' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/doubleClick' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/dragAndDrop' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/getAttribute' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/getCSSProperty' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/getHTML' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/getLocation' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/getProperty' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/getSize' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/getTagName' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/getText' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/getValue' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/isDisplayed' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/isDisplayedInViewport' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/isEnabled' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/isExisting' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/isFocused' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/isSelected' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/moveTo' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/saveScreenshot' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/scrollIntoView' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/selectByAttribute' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/selectByIndex' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/selectByVisibleText' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/setValue' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/shadow$' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/shadow$$' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/touchAction' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/waitForDisplayed' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/waitForEnabled' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/waitForExist' {
  declare module.exports: any;
}

declare module 'webdriverio/build/commands/element/waitUntil' {
  declare module.exports: any;
}

declare module 'webdriverio/build/constants' {
  declare module.exports: any;
}

declare module 'webdriverio/build/index' {
  declare module.exports: any;
}

declare module 'webdriverio/build/middlewares' {
  declare module.exports: any;
}

declare module 'webdriverio/build/multiremote' {
  declare module.exports: any;
}

declare module 'webdriverio/build/scripts/getHTML' {
  declare module.exports: any;
}

declare module 'webdriverio/build/scripts/getProperty' {
  declare module.exports: any;
}

declare module 'webdriverio/build/scripts/isDisplayedInViewport' {
  declare module.exports: any;
}

declare module 'webdriverio/build/scripts/isFocused' {
  declare module.exports: any;
}

declare module 'webdriverio/build/scripts/newWindow' {
  declare module.exports: any;
}

declare module 'webdriverio/build/scripts/shadowFnFactory' {
  declare module.exports: any;
}

declare module 'webdriverio/build/utils' {
  declare module.exports: any;
}

declare module 'webdriverio/build/utils/refetchElement' {
  declare module.exports: any;
}

declare module 'webdriverio/build/utils/Timer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webdriverio/build/commands/browser/$.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/$'>;
}
declare module 'webdriverio/build/commands/browser/$$.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/$$'>;
}
declare module 'webdriverio/build/commands/browser/call.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/call'>;
}
declare module 'webdriverio/build/commands/browser/debug.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/debug'>;
}
declare module 'webdriverio/build/commands/browser/deleteCookies.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/deleteCookies'>;
}
declare module 'webdriverio/build/commands/browser/execute.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/execute'>;
}
declare module 'webdriverio/build/commands/browser/executeAsync.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/executeAsync'>;
}
declare module 'webdriverio/build/commands/browser/getCookies.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/getCookies'>;
}
declare module 'webdriverio/build/commands/browser/keys.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/keys'>;
}
declare module 'webdriverio/build/commands/browser/newWindow.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/newWindow'>;
}
declare module 'webdriverio/build/commands/browser/pause.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/pause'>;
}
declare module 'webdriverio/build/commands/browser/reloadSession.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/reloadSession'>;
}
declare module 'webdriverio/build/commands/browser/saveScreenshot.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/saveScreenshot'>;
}
declare module 'webdriverio/build/commands/browser/setCookies.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/setCookies'>;
}
declare module 'webdriverio/build/commands/browser/setTimeout.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/setTimeout'>;
}
declare module 'webdriverio/build/commands/browser/switchWindow.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/switchWindow'>;
}
declare module 'webdriverio/build/commands/browser/touchAction.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/touchAction'>;
}
declare module 'webdriverio/build/commands/browser/url.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/url'>;
}
declare module 'webdriverio/build/commands/browser/waitUntil.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/browser/waitUntil'>;
}
declare module 'webdriverio/build/commands/constant.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/constant'>;
}
declare module 'webdriverio/build/commands/element/$.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/$'>;
}
declare module 'webdriverio/build/commands/element/$$.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/$$'>;
}
declare module 'webdriverio/build/commands/element/addValue.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/addValue'>;
}
declare module 'webdriverio/build/commands/element/clearValue.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/clearValue'>;
}
declare module 'webdriverio/build/commands/element/click.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/click'>;
}
declare module 'webdriverio/build/commands/element/doubleClick.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/doubleClick'>;
}
declare module 'webdriverio/build/commands/element/dragAndDrop.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/dragAndDrop'>;
}
declare module 'webdriverio/build/commands/element/getAttribute.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/getAttribute'>;
}
declare module 'webdriverio/build/commands/element/getCSSProperty.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/getCSSProperty'>;
}
declare module 'webdriverio/build/commands/element/getHTML.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/getHTML'>;
}
declare module 'webdriverio/build/commands/element/getLocation.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/getLocation'>;
}
declare module 'webdriverio/build/commands/element/getProperty.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/getProperty'>;
}
declare module 'webdriverio/build/commands/element/getSize.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/getSize'>;
}
declare module 'webdriverio/build/commands/element/getTagName.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/getTagName'>;
}
declare module 'webdriverio/build/commands/element/getText.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/getText'>;
}
declare module 'webdriverio/build/commands/element/getValue.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/getValue'>;
}
declare module 'webdriverio/build/commands/element/isDisplayed.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/isDisplayed'>;
}
declare module 'webdriverio/build/commands/element/isDisplayedInViewport.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/isDisplayedInViewport'>;
}
declare module 'webdriverio/build/commands/element/isEnabled.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/isEnabled'>;
}
declare module 'webdriverio/build/commands/element/isExisting.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/isExisting'>;
}
declare module 'webdriverio/build/commands/element/isFocused.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/isFocused'>;
}
declare module 'webdriverio/build/commands/element/isSelected.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/isSelected'>;
}
declare module 'webdriverio/build/commands/element/moveTo.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/moveTo'>;
}
declare module 'webdriverio/build/commands/element/saveScreenshot.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/saveScreenshot'>;
}
declare module 'webdriverio/build/commands/element/scrollIntoView.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/scrollIntoView'>;
}
declare module 'webdriverio/build/commands/element/selectByAttribute.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/selectByAttribute'>;
}
declare module 'webdriverio/build/commands/element/selectByIndex.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/selectByIndex'>;
}
declare module 'webdriverio/build/commands/element/selectByVisibleText.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/selectByVisibleText'>;
}
declare module 'webdriverio/build/commands/element/setValue.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/setValue'>;
}
declare module 'webdriverio/build/commands/element/shadow$.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/shadow$'>;
}
declare module 'webdriverio/build/commands/element/shadow$$.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/shadow$$'>;
}
declare module 'webdriverio/build/commands/element/touchAction.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/touchAction'>;
}
declare module 'webdriverio/build/commands/element/waitForDisplayed.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/waitForDisplayed'>;
}
declare module 'webdriverio/build/commands/element/waitForEnabled.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/waitForEnabled'>;
}
declare module 'webdriverio/build/commands/element/waitForExist.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/waitForExist'>;
}
declare module 'webdriverio/build/commands/element/waitUntil.js' {
  declare module.exports: $Exports<'webdriverio/build/commands/element/waitUntil'>;
}
declare module 'webdriverio/build/constants.js' {
  declare module.exports: $Exports<'webdriverio/build/constants'>;
}
declare module 'webdriverio/build/index.js' {
  declare module.exports: $Exports<'webdriverio/build/index'>;
}
declare module 'webdriverio/build/middlewares.js' {
  declare module.exports: $Exports<'webdriverio/build/middlewares'>;
}
declare module 'webdriverio/build/multiremote.js' {
  declare module.exports: $Exports<'webdriverio/build/multiremote'>;
}
declare module 'webdriverio/build/scripts/getHTML.js' {
  declare module.exports: $Exports<'webdriverio/build/scripts/getHTML'>;
}
declare module 'webdriverio/build/scripts/getProperty.js' {
  declare module.exports: $Exports<'webdriverio/build/scripts/getProperty'>;
}
declare module 'webdriverio/build/scripts/isDisplayedInViewport.js' {
  declare module.exports: $Exports<'webdriverio/build/scripts/isDisplayedInViewport'>;
}
declare module 'webdriverio/build/scripts/isFocused.js' {
  declare module.exports: $Exports<'webdriverio/build/scripts/isFocused'>;
}
declare module 'webdriverio/build/scripts/newWindow.js' {
  declare module.exports: $Exports<'webdriverio/build/scripts/newWindow'>;
}
declare module 'webdriverio/build/scripts/shadowFnFactory.js' {
  declare module.exports: $Exports<'webdriverio/build/scripts/shadowFnFactory'>;
}
declare module 'webdriverio/build/utils.js' {
  declare module.exports: $Exports<'webdriverio/build/utils'>;
}
declare module 'webdriverio/build/utils/refetchElement.js' {
  declare module.exports: $Exports<'webdriverio/build/utils/refetchElement'>;
}
declare module 'webdriverio/build/utils/Timer.js' {
  declare module.exports: $Exports<'webdriverio/build/utils/Timer'>;
}
