// flow-typed signature: 3fa8c30d207f52d91e0860ca9ce11210
// flow-typed version: <<STUB>>/@babel/plugin-transform-modules-umd_v^7.2.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-modules-umd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-modules-umd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-modules-umd/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-modules-umd/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-modules-umd/lib/index'>;
}
